// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"

	"encore.dev/types/uuid"
)

type Avatar struct {
	ID      uuid.UUID
	FileID  string
	BotName string
	Url     string
	Deleted sql.NullTime
}
