// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	DeleteAvatar(ctx context.Context, db DBTX, botName string) (*Avatar, error)
	GetAvatar(ctx context.Context, db DBTX, botName string) (*Avatar, error)
	InsertAvatar(ctx context.Context, db DBTX, arg InsertAvatarParams) (*Avatar, error)
}

var _ Querier = (*Queries)(nil)
