package chat

import (
	"encore.app/chat/provider"
	client "encore.app/chat/service/clients"
	llm "encore.app/llm/service"
	"encore.dev/pubsub"
)

// provider-message-sub is a subscription to the provider message topic. It handles
// all incoming messages from the providers.
var _ = pubsub.NewSubscription(
	provider.MessageTopic, "provider-message-sub",
	pubsub.SubscriptionConfig[*client.Message]{
		Handler: pubsub.MethodHandler((*Service).ProcessInboundMessage),
	},
)

// bot-messages-sub is a subscription to the bot message topic. It handles
// messages generated by the llm providers
var _ = pubsub.NewSubscription(
	llm.BotMessageTopic, "bot-messages-sub",
	pubsub.SubscriptionConfig[*llm.BotResponse]{
		Handler: pubsub.MethodHandler((*Service).ProcessBotMessage),
	},
)
