package chat

import (
	"encore.app/chat/provider"
	client "encore.app/chat/service/client"
	llm "encore.app/llm/service"
	"encore.dev/pubsub"
)

// provider-message-sub is a subscription to the provider message topic. It handles
// all incoming messages from the providers.
//
// This uses Encore's pubsub package, learn more: https://encore.dev/docs/primitives/pubsub
var _ = pubsub.NewSubscription(
	provider.InboxTopic, "provider-message-sub",
	pubsub.SubscriptionConfig[*client.Message]{
		Handler: pubsub.MethodHandler((*Service).ProcessProviderMessage),
	},
)

// llm-messages-sub is a subscription to the llm message topic. It handles
// messages generated by the llm providers
//
// This uses Encore's pubsub package, learn more: https://encore.dev/docs/primitives/pubsub
var _ = pubsub.NewSubscription(
	llm.LLMMessageTopic, "llm-message-sub",
	pubsub.SubscriptionConfig[*llm.BotResponse]{
		Handler: pubsub.MethodHandler((*Service).ProcessLLMMessage),
	},
)
