import { FC, useCallback, useEffect, useState } from "react";

import {
  Avatar,
  ChatContainer,
  ConversationHeader,
  MainContainer,
  Message,
  MessageGroup,
  MessageInput,
  MessageList,
  Sidebar,
  TypingIndicator,
} from "@chatscope/chat-ui-kit-react";

import {
  ChatMessage,
  Conversation as Conv,
  MessageContent,
  MessageContentType,
  MessageDirection,
  MessageStatus,
  Participant,
  TextContent,
  useChat,
  User,
} from "@chatscope/use-chat";
import { ExampleChatService } from "./ChatService";
import ProfileModal from "./ProfileModal";
import AddBotModal, { AddBotStatus } from "./AddBotModal";
import {
  Robot,
  Spinner,
  User as UserIcon,
  WarningCircle,
} from "@phosphor-icons/react";
import poweredBy from "../assets/powered-by-encore.png";
import InviteFriendModal from "./InviteFriendModal.tsx";

const WHITE = "#dcdee1";

export const Chat = ({
  user,
  channelID,
}: {
  user: User;
  channelID: string;
}) => {
  // Get all chat related values and methods from useChat hook
  const {
    addConversation,
    currentMessages,
    activeConversation,
    setActiveConversation,
    sendMessage,
    getUser,
    currentMessage,
    setCurrentMessage,
    sendTyping,
    setCurrentUser,
    service,
    addUser,
  } = useChat();

  useState(() => {
    let conv = new Conv({
      id: channelID,
      participants: [new Participant({ id: user.id })],
    });
    addConversation(conv);
    return conv;
  });

  const [botStatus, setBotStatus] = useState<AddBotStatus | undefined>();

  const chatService = service as ExampleChatService;
  useEffect(() => {
    addUser(user);
    setActiveConversation(channelID);
    chatService.joinChannel(channelID);
  }, []);

  useEffect(() => {
    setCurrentUser(user);
  }, [user, setCurrentUser]);

  const [userProfile, setUserProfile] = useState<User>();
  const [addUserShow, setAddUserShow] = useState(false);
  const [inviteFriendShow, setInviteFriend] = useState(false);

  const handleChange = (value: string) => {
    // Send typing indicator to the active conversation
    // You can call this method on each onChange event
    // because sendTyping method can throttle sending this event
    // So typing event will not be send to often to the server
    setCurrentMessage(value);
    if (activeConversation) {
      sendTyping({
        conversationId: activeConversation?.id,
        isTyping: true,
        userId: user.id,
        content: value, // Note! Most often you don't want to send what the user types, as this can violate his privacy!
        throttle: true,
      });
    }
  };

  const handleSend = (text: string) => {
    const message = new ChatMessage({
      id: "", // Id will be generated by storage generator, so here you can pass an empty string
      content: text as unknown as MessageContent<TextContent>,
      contentType: MessageContentType.TextHtml,
      senderId: user.id,
      direction: MessageDirection.Outgoing,
      status: MessageStatus.Sent,
    });

    if (activeConversation) {
      sendMessage({
        message,
        conversationId: activeConversation.id,
        senderId: user.id,
      });
    }
  };

  const getTypingIndicator = useCallback(() => {
    if (activeConversation) {
      const typingUsers = activeConversation.typingUsers;

      if (typingUsers.length > 0) {
        const typingUserId = typingUsers.items[0].userId;

        // Check if typing user participates in the conversation
        if (activeConversation.participantExists(typingUserId)) {
          const typingUser = getUser(typingUserId);

          if (typingUser) {
            return (
              <TypingIndicator
                className="!bg-transparent !px-4"
                content={`${typingUser.username} is typing`}
              />
            );
          }
        }
      }
    }

    return null;
  }, [activeConversation, getUser]);

  return (
    <MainContainer responsive className="w-full h-screen !border-none">
      <ProfileModal
        show={userProfile !== undefined}
        user={userProfile}
        onHide={() => setUserProfile(undefined)}
      />

      <AddBotModal
        statusChange={(s?: AddBotStatus) => setBotStatus(s)}
        show={addUserShow}
        channelID={channelID}
        onHide={() => setAddUserShow(false)}
      />

      <InviteFriendModal
        show={inviteFriendShow}
        channelID={channelID}
        onHide={() => setInviteFriend(false)}
      />

      <Sidebar
        position="left"
        scrollable
        className="flex justify-between !bg-gray-900 !border-none !max-w-[220px] !shadow-xl py-2"
      >
        <div>
          {activeConversation?.participants.map((p) => {
            const isUser = p.id === user.id;
            return (
              <div
                id={p.id}
                className={`
                  flex space-x-2 items-center px-4 py-3 hover:!bg-gray-800
                  ${isUser ? "cursor-default" : "cursor-pointer"}
                `}
                onClick={() => {
                  if (!isUser) setUserProfile(getUser(p.id));
                }}
              >
                <Avatar status="available" src={getUser(p.id)?.avatar}>
                  {isUser && <ProfileCircle user={user} />}
                </Avatar>
                <div>
                  <span className="text-white font-semibold">
                    {getUser(p.id)?.username}
                  </span>
                </div>
              </div>
            );
          })}

          {botStatus?.status === "creating" && (
            <div className="flex space-x-2 items-center p-4 py-3 cursor-pointer">
              <Avatar status="eager" size="sm">
                <Spinner size={40} color={WHITE} className="animate-spin" />
              </Avatar>
              <div className="text-white">Creating {botStatus?.botName}</div>
            </div>
          )}

          {botStatus?.status === "failure" && (
            <div className="flex space-x-2 items-center p-4 py-3 cursor-pointer">
              <Avatar status="dnd">
                <WarningCircle size={40} color={WHITE} />
              </Avatar>
              <div className="text-white">
                Failed to create {botStatus?.botName}
              </div>
            </div>
          )}

          <div className="h-[2px] w-5/6 bg-gray-700 mx-auto my-4" />

          <div
            onClick={() => setAddUserShow(true)}
            className="flex items-center space-x-2 text-white px-4 py-2 cursor-pointer hover:!bg-gray-800"
          >
            <div>
              <Robot size={25} color={WHITE} />
            </div>
            <span className="uppercase text-xs hidden md:block">Add Bot</span>
          </div>

          <div
            onClick={() => setInviteFriend(true)}
            className="flex items-center space-x-2 text-white px-4 py-2 cursor-pointer hover:!bg-gray-800"
          >
            <div>
              <UserIcon size={25} color={WHITE} />
            </div>
            <span className="uppercase text-xs hidden md:block">
              Invite Friend
            </span>
          </div>
        </div>

        <div className="px-2">
          <a href="https://github.com/encoredev/ai-chat/tree/main">
            <img
              src={poweredBy}
              alt="Powered by Encore"
              className="block mx-auto"
            />
          </a>
        </div>
      </Sidebar>

      <ChatContainer>
        <ConversationHeader className="!bg-gray-900 !p-0 !border-gray-500 shadow-lg">
          <ConversationHeader.Back />
          <ConversationHeader.Content>
            <p className="flex font-mono items-center space-x-2 text-white font-semibold px-4 py-2">
              <span className="opacity-50 text-xl">#</span>{" "}
              <span className="text-sm">{channelID}</span>
            </p>
          </ConversationHeader.Content>
        </ConversationHeader>
        <MessageList
          typingIndicator={getTypingIndicator()}
          className="!bg-gray-800"
        >
          {currentMessages.map((g) => (
            <MessageGroup key={g.id}>
              <MessageGroup.Messages>
                {g.messages.map((m: ChatMessage<MessageContentType>) => (
                  <Message
                    key={m.id}
                    className="w-full !p-2 hover:bg-gray-700 transition"
                    model={{
                      type: "custom",
                      direction: "incoming",
                      position: "normal",
                    }}
                    avatarPosition="tl"
                  >
                    <Avatar
                      name={m.senderId}
                      status="available"
                      src={getUser(m.senderId)?.avatar}
                    >
                      {m.senderId === user.id && <ProfileCircle user={user} />}
                    </Avatar>
                    <Message.CustomContent className="-mt-2 text-white">
                      <p className="flex items-center space-x-3">
                        <span className="font-semibold">
                          {getUser(m.senderId)?.username}
                        </span>
                        <span className="text-gray-500 text-xs">
                          {getTodaysDate()}
                        </span>
                      </p>
                      <p>{m.content as unknown as string}</p>
                    </Message.CustomContent>
                  </Message>
                ))}
              </MessageGroup.Messages>
            </MessageGroup>
          ))}
        </MessageList>
        <MessageInput
          className="!bg-gray-800 !border-none !pb-4 !pr-3"
          value={currentMessage}
          onChange={handleChange}
          onSend={handleSend}
          disabled={!activeConversation}
          attachButton={false}
          placeholder="Type here..."
        />
      </ChatContainer>
    </MainContainer>
  );
};

const ProfileCircle: FC<{ user?: User }> = ({ user }) => {
  return (
    <figure className="flex items-center justify-center rounded-full bg-blue h-[40px] w-[40px] relative uppercase text-white text-lg font-semibold">
      {user?.username[0]}
      {user?.username[1]}
    </figure>
  );
};

const getTodaysDate = () => {
  const date = new Date();
  const [year, month, day] = date.toISOString().split("T")[0].split("-");
  return `${day}/${month}/${year}`;
};
